services:
  backend:
    build:
      context: ./BACKEND
    container_name: todo-backend
    environment:
      - DATABASE_PATH=/app/data/db.sqlite3
    volumes:
      - backend_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./FRONTEND
    container_name: todo-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: